AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a lambda function to check if ECS Container Insights enabled across ECS clusters
Parameters:
  bktName:
    Type: String
    Description: Name of the bucket holding the lambda zip (do NOT precede with s3://)
    Default: ecs-check-container-insights-bkt
  zipName:
    Type: String
    Description: Name of the lambda zip file
    Default: ecsContainerInsightsCheck-c357bbc9-e595-42c8-90c2-810aca3be888.zip
Resources:
  checkECSFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Lambda function to check if ECS Container Insights is enabled across clusters
      Handler: lambda_function.lambda_handler
      Timeout: 10
      Role:
        Fn::GetAtt:
        - lambdaIAMRole
        - Arn
      Code:
        S3Bucket: !Ref bktName
        S3Key: !Ref zipName
      Runtime: python3.8
      FunctionName:
        Fn::Sub: ecsContainerInsightsCheck
  lambdaIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
      Policies:
      - PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: '*'
          - Action:
            - ecs:Describe*
            - ecs:List*
            Effect: Allow
            Resource: '*'
        PolicyName:
          Fn::Sub: lambda-ecsContainerInsightsCheck
